
services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/.env
    volumes:
      - ../frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

  contract:
    build:
      context: ..
      dockerfile: docker/contract.Dockerfile
    container_name: contract
    ports:
      - "8545:8545"
    env_file:
      - ../contract/.env
    volumes:
      - ../contract:/app
    restart: unless-stopped
